### ISSUE TITLE
Encode dataset name as user-defined field

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/proc_dash#10]
Currently, assuming that all input csvs to the dashboard have the same name (`bagel.csv`), I don't think there's a way to derive the name of the dataset from the input. However, having this info could be helpful for displaying the dataset name at the top of the dashboard, esp if a user wants to visualize bagels for multiple datasets. Maybe we could bake this (pun intended) into the bagel.csv - such as a column with the dataset name? I would expect it to be the same for all rows.

Edit:
- [ ] Allow user to input the dataset name when uploading a bagel

**Comment by alyssadai** [comment]
@nikhil153, thoughts?

**Comment by nikhil153** [comment]
I agree having dataset info in dashboard would be useful. I guess the question would be what other dataset-level info do we want display apart from the name? Would it be useful to have things like available modalities, number of visits, containers used etc as well? If that's the case, then we may want to input a separate `global_config` to the dashboard to simplify this process rather than trying to derive everything from the bagel.csv.
